env:
  global:
    - CC_TEST_REPORTER_ID=129c301e012f372dc091f004949f88cc1f004a7119f65776dceab851205991f2

language: python
python: "3.5.5"
cache: pip

install:
  - export PROJECT_DIR=`pwd`
  - cd /tmp
  - git clone https://github.com/uclouvain/osis.git
  - cd osis
  - git submodule init
  - git submodule update
  - pip install -r requirements.txt
  - rm -Rf osis_common
  - ln -s $PROJECT_DIR osis_common

before_script:
  - cp .env.example .env
  - echo 'APPS_TO_TEST += ("osis_common",)' >> backoffice/settings/local.py
  - echo >> .env
  - echo "POSTGRES_USER = 'postgres'" >> .env
  - echo "POSTGRES_PASSWORD = ''" >> .env
  - psql -d template1 -c 'create extension unaccent;' -U postgres
  - psql -c 'create database osis_local;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - python3 manage.py compilemessages && coverage run manage.py test osis_common --exclude-tag=selenium --no-logs

after_script:
  - coverage xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.4