# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-15 21:52
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content_txt', models.TextField()),
                ('content_html', models.TextField()),
                ('receiver_id', models.IntegerField()),
                ('created', models.DateTimeField(editable=False)),
                ('sent', models.DateTimeField(null=True)),
                ('reference', models.CharField(db_index=True, max_length=100, null=True)),
                ('show_to_user', models.BooleanField(default=True)),
                ('read_by_user', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('template', ckeditor.fields.RichTextField()),
                ('format', models.CharField(choices=[('PLAIN', 'plain'), ('HTML', 'HTML'), ('PLAIN_HTML', 'plain_and_html')], max_length=15)),
                ('language', models.CharField(choices=[('fr-be', 'French'), ('en', 'English')], default='fr-be', max_length=30)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='messagetemplate',
            unique_together={('reference', 'language')},
        ),
    ]
