# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-18 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osis_common', '0002_documentfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentfile',
            name='physical_extension',
        ),
        migrations.RemoveField(
            model_name='documentfile',
            name='physical_name',
        ),
    ]
