# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-19 13:06
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_common', '0003_auto_20160718_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='content_type',
            field=models.CharField(choices=[('application/csv', 'application/csv'), ('application/doc', 'application/doc'), ('application/pdf', 'application/pdf'), ('application/xls', 'application/xls'), ('application/xlsx', 'application/xlsx'), ('application/xml', 'application/xml'), ('application/zip', 'application/zip'), ('image/jpeg', 'image/jpeg'), ('image/gif', 'image/gif'), ('image/png', 'image/png'), ('text/html', 'text/html'), ('text/plain', 'text/plain')], default='application/csv', max_length=50),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/endloril/python/projects/osis/osis-portal/uploads'), upload_to=''),
        ),
    ]
