# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-08 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_common', '0003_modification_choix_description_01'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='description',
            field=models.CharField(choices=[('ID_CARD', 'identity_card'), ('LETTER_MOTIVATION', 'letter_motivation'), ('ID_PICTURE', 'id_picture'), ('NATIONAL_DIPLOMA_VERSO', 'national_diploma_verso'), ('NATIONAL_DIPLOMA_RECTO', 'national_diploma_recto'), ('INTERNATIONAL_DIPLOMA_VERSO', 'international_diploma_verso'), ('INTERNATIONAL_DIPLOMA_RECTO', 'international_diploma_recto'), ('TRANSLATED_INTERNATIONAL_DIPLOMA_VERSO', 'translated_international_diploma_verso'), ('TRANSLATED_INTERNATIONAL_DIPLOMA_RECTO', 'translated_international_diploma_recto'), ('HIGH_SCHOOL_SCORES_TRANSCRIPT_RECTO', 'high_school_scores_transcript_recto'), ('HIGH_SCHOOL_SCORES_TRANSCRIPT_VERSO', 'high_school_scores_transcript_verso'), ('TRANSLATED_HIGH_SCHOOL_SCORES_TRANSCRIPT_RECTO', 'translated_high_school_scores_transcript_recto'), ('TRANSLATED_HIGH_SCHOOL_SCORES_TRANSCRIPT_VERSO', 'translated_high_school_scores_transcript_verso'), ('EQUIVALENCE', 'equivalence'), ('ADMISSION_EXAM_CERTIFICATE', 'admission_exam_certificate'), ('PROFESSIONAL_EXAM_CERTIFICATE', 'professional_exam_certificate')], default='LETTER_MOTIVATION', max_length=50),
        ),
    ]
