# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_common', '0004_modification_choix_description_02'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagehistory',
            name='receiver_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
