# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-17 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_common', '0005_message_history_add_index_on_receiver_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentfile',
            old_name='document_type',
            new_name='application_name',
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
