# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-26 12:56
from __future__ import unicode_literals

import uuid

from django.db import migrations

from osis_common.models.document_file import DocumentFile


def populate_document_file_uuid(apps, schema_editor):
    document_files_ids = DocumentFile.objects.values_list('id',flat=True)
    for id in document_files_ids:
        DocumentFile.objects.filter(pk=id).update(uuid=uuid.uuid4())


class Migration(migrations.Migration):
    dependencies = [
        ('osis_common', '0007_documentfile_uuid'),
    ]

    operations = [
        migrations.RunPython(populate_document_file_uuid),
    ]
