# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 07:46
from __future__ import unicode_literals

from django.db import migrations, models
from osis_common.models.document_file import DocumentFile


def migrate_user_to_username(apps, schema_editor):
    document_files = DocumentFile.objects.all()
    for document_file in document_files:
        document_file.username = document_file.user.username
        document_file.save()


class Migration(migrations.Migration):

    dependencies = [
        ('osis_common', '0009_set_document_file_uuid_not_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfile',
            name='username',
            field=models.CharField(default='system', max_length=75, db_index=True),
        ),
        migrations.RunPython(migrate_user_to_username),
        migrations.RemoveField(
            model_name='documentfile',
            name='user',
        ),
    ]
