# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-22 14:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osis_common', '0009_set_document_file_uuid_not_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
