# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_common', '0009_set_document_file_uuid_not_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfile',
            name='username',
            field=models.CharField(default='system', max_length=254, db_index=True),
        ),
        migrations.RemoveField(
            model_name='documentfile',
            name='user',
        ),
    ]
