# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-27 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osis_common', '0010_documentfile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentfile',
            old_name='username',
            new_name='update_by',
        ),
    ]
