# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-23 16:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_common', '0011_rename_username_to_update_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_name', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('message', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('exception_title', models.CharField(max_length=255)),
                ('exception', models.TextField()),
            ],
        ),
    ]
