# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-20 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_common', '0012_queueexception'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('notice', models.TextField()),
                ('start_publish', models.DateTimeField()),
                ('stop_publish', models.DateTimeField()),
            ],
        ),
    ]
