# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-20 08:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_common', '0013_applicationnotice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageQueueCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.CharField(max_length=255)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('changed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
