# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-03 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_common', '0014_messagequeuecache'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagehistory',
            name='receiver_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
