# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-06 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osis_common', '0016_populate_message_history_receiver_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagehistory',
            old_name='receiver_id',
            new_name='receiver_person_id',
        ),
    ]
