# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-30 10:01
from __future__ import unicode_literals

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osis_common', '0018_auto_20190506_1610'),
    ]

    operations = [
        UnaccentExtension()
    ]
