# Generated by Django 3.2.12 on 2022-10-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_common', '0019_auto_20201112_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
