# Generated by Django 3.2.12 on 2022-02-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('osis_common', '0019_auto_20201112_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagequeuecache',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='queueexception',
            name='message',
            field=models.JSONField(null=True),
        ),
    ]
