# Generated by Django 3.2.19 on 2023-06-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_common', '0021_auto_20220211_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('transaction_id', models.UUIDField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(default=False)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
