# Generated by Django 3.2.19 on 2023-06-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_common', '0022_outbox'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outbox',
            options={'verbose_name_plural': 'outbox'},
        ),
        migrations.AlterField(
            model_name='outbox',
            name='transaction_id',
            field=models.UUIDField(unique=True),
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer', models.CharField(max_length=255)),
                ('event_name', models.CharField(max_length=255)),
                ('transaction_id', models.UUIDField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'inbox',
                'unique_together': {('consumer', 'transaction_id')},
            },
        ),
    ]
