# Generated by Django 3.2.25 on 2024-10-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_common', '0022_inbox_outbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='attempts_number',
            field=models.IntegerField(default=0),
        ),
    ]
