# Generated by Django 3.2.19 on 2023-06-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_common', '0023_auto_20230613_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='completed_date',
            new_name='last_execution_date',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='completed',
        ),
        migrations.AddField(
            model_name='inbox',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Done'), ('ERROR', 'Error')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='inbox',
            name='traceback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
