# Generated by Django 3.2.25 on 2024-10-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_common', '0023_inbox_attempts_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Done'), ('ERROR', 'Error'), ('DEAD_LETTER', 'Dead letter')], default='PENDING', max_length=15),
        ),
    ]
