# Generated by Django 4.2.16 on 2025-03-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_common', '0024_alter_inbox_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxArchived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer', models.CharField(max_length=255)),
                ('event_name', models.CharField(max_length=255)),
                ('transaction_id', models.UUIDField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Done'), ('ERROR', 'Error'), ('DEAD_LETTER', 'Dead letter')], default='PENDING', max_length=15)),
                ('last_execution_date', models.DateTimeField(blank=True, null=True)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('attempts_number', models.IntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'inbox archived',
            },
        ),
        migrations.CreateModel(
            name='OutboxArchived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('transaction_id', models.UUIDField(unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(default=False)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'Outbox archived',
            },
        ),
        migrations.AddField(
            model_name='inbox',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='outbox',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
