# Generated by Django 4.2.16 on 2025-03-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_common', '0025_inboxarchived_outboxarchived_inbox_meta_outbox_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxarchived',
            name='creation_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='outboxarchived',
            name='creation_date',
            field=models.DateTimeField(),
        ),
    ]
